/*
 *
 * Confidential Information of Telekinesys Research Limited (t/a Havok). Not for disclosure or distribution without Havok's
 * prior written consent. This software contains code, techniques and know-how which is confidential and proprietary to Havok.
 * Product and Trade Secret source code contains trade secrets of Havok. Havok Software (C) Copyright 1999-2014 Telekinesys Research Limited t/a Havok. All Rights Reserved. Use of this software is subject to the terms of an end user license agreement.
 *
 */

//HK_REFLECTION_PARSER_EXCLUDE_FILE

// Autogenerated by generateReflections.py (projectClassList.py)
// Changes will not be lost unless:
// - The workspace is re-generated using build.py
// - The corresponding reflection database (reflection.db) is deleted
// - The --force-output or --force-rebuild option is added to the pre-build generateReflection.py execution

HK_CLASS(HK_EXPORT_AI,hkaiEdgeGeometry)
HK_CLASS(HK_EXPORT_AI,hkaiNavMeshGenerationSettings)
HK_CLASS(HK_EXPORT_AI,hkaiNavVolumeGenerationSettings)
HK_STRUCT(HK_EXPORT_AI,hkaiEdgeGeometryEdge)
HK_STRUCT(HK_EXPORT_AI,hkaiEdgeGeometryFace)
HK_STRUCT(HK_EXPORT_AI,hkaiNavMeshEdgeMatchingParameters)
HK_STRUCT(HK_EXPORT_AI,hkaiNavMeshGenerationSettingsMaterialConstructionPair)
HK_STRUCT(HK_EXPORT_AI,hkaiNavMeshGenerationSettingsOverrideSettings)
HK_STRUCT(HK_EXPORT_AI,hkaiNavMeshGenerationSettingsRegionPruningSettings)
HK_STRUCT(HK_EXPORT_AI,hkaiNavMeshGenerationSettingsWallClimbingSettings)
HK_STRUCT(HK_EXPORT_AI,hkaiNavMeshSimplificationUtilsExtraVertexSettings)
HK_STRUCT(HK_EXPORT_AI,hkaiNavMeshSimplificationUtilsSettings)
HK_STRUCT(HK_EXPORT_AI,hkaiNavVolumeGenerationSettingsChunkSettings)
HK_STRUCT(HK_EXPORT_AI,hkaiNavVolumeGenerationSettingsMaterialConstructionInfo)
HK_STRUCT(HK_EXPORT_AI,hkaiNavVolumeGenerationSettingsMergingSettings)

/*
 * Havok SDK - Base file, BUILD(#20140618)
 * 
 * Confidential Information of Havok.  (C) Copyright 1999-2014
 * Telekinesys Research Limited t/a Havok. All Rights Reserved. The Havok
 * Logo, and the Havok buzzsaw logo are trademarks of Havok.  Title, ownership
 * rights, and intellectual property rights in the Havok software remain in
 * Havok and/or its suppliers.
 * 
 * Use of this software for evaluation purposes is subject to and indicates
 * acceptance of the End User licence Agreement for this product. A copy of
 * the license is included with this software and is also available from salesteam@havok.com.
 * 
 */
