/*
 *
 * Confidential Information of Telekinesys Research Limited (t/a Havok). Not for disclosure or distribution without Havok's
 * prior written consent. This software contains code, techniques and know-how which is confidential and proprietary to Havok.
 * Product and Trade Secret source code contains trade secrets of Havok. Havok Software (C) Copyright 1999-2014 Telekinesys Research Limited t/a Havok. All Rights Reserved. Use of this software is subject to the terms of an end user license agreement.
 *
 */

//HK_REFLECTION_PARSER_EXCLUDE_FILE

// Autogenerated by generateReflections.py (projectClassList.py)
// Changes will not be lost unless:
// - The workspace is re-generated using build.py
// - The corresponding reflection database (reflection.db) is deleted
// - The --force-output or --force-rebuild option is added to the pre-build generateReflection.py execution

#include "Reflections/hkaiAstarCostModifierReflection.cpp"
#include "Reflections/hkaiDefaultAstarCostModifierReflection.cpp"
#include "Reflections/hkaiAstarEdgeFilterReflection.cpp"
#include "Reflections/hkaiDefaultAstarEdgeFilterReflection.cpp"
#include "Reflections/hkaiSearchParamsReflection.cpp"
#include "Reflections/hkaiAstarParametersReflection.cpp"
#include "Reflections/hkaiEdgePathReflection.cpp"
#include "Reflections/hkaiObstacleGeneratorReflection.cpp"
#include "Reflections/hkaiSimpleObstacleGeneratorReflection.cpp"
#include "Reflections/hkaiAvoidanceSolverReflection.cpp"
#include "Reflections/hkaiLocalSteeringInputReflection.cpp"
#include "Reflections/hkaiAdaptiveRangerReflection.cpp"
#include "Reflections/hkaiPathFollowingUtilReflection.cpp"
#include "Reflections/hkaiCharacterReflection.cpp"
#include "Reflections/hkaiPathReflection.cpp"
#include "Reflections/hkaiDynamicNavMeshQueryMediatorReflection.cpp"
#include "Reflections/hkaiNavMeshQueryMediatorReflection.cpp"
#include "Reflections/hkaiStaticTreeNavMeshQueryMediatorReflection.cpp"
#include "Reflections/hkaiAabbTreeNavVolumeMediatorReflection.cpp"
#include "Reflections/hkaiDynamicNavVolumeMediatorReflection.cpp"
#include "Reflections/hkaiNavVolumeMediatorReflection.cpp"
#include "Reflections/hkaiCarverReflection.cpp"
#include "Reflections/hkaiInvertedAabbVolumeReflection.cpp"
#include "Reflections/hkaiMaterialPainterReflection.cpp"
#include "Reflections/hkaiPlaneVolumeReflection.cpp"
#include "Reflections/hkaiReferenceFrameReflection.cpp"
#include "Reflections/hkaiVolumeReflection.cpp"
#include "Reflections/hkaiNavMeshCutterReflection.cpp"
#include "Reflections/hkaiOverlapManagerReflection.cpp"
#include "Reflections/hkaiReferenceFrameAndExtrusionReflection.cpp"
#include "Reflections/hkaiSilhouetteGeneratorSectionContextReflection.cpp"
#include "Reflections/hkaiPhysicsBodySilhouetteGeneratorBaseReflection.cpp"
#include "Reflections/hkaiPointCloudSilhouetteGeneratorReflection.cpp"
#include "Reflections/hkaiSilhouetteGenerationParametersReflection.cpp"
#include "Reflections/hkaiSilhouetteGeneratorReflection.cpp"
#include "Reflections/hkaiSilhouetteReferenceFrameReflection.cpp"
#include "Reflections/hkaiConvexSilhouetteReflection.cpp"
#include "Reflections/hkaiAgentTraversalInfoReflection.cpp"
#include "Reflections/hkaiDirectedGraphExplicitCostReflection.cpp"
#include "Reflections/hkaiDirectedGraphInstanceReflection.cpp"
#include "Reflections/hkaiGraphPathSearchParametersReflection.cpp"
#include "Reflections/hkaiStreamingCollectionReflection.cpp"
#include "Reflections/hkaiStreamingSetReflection.cpp"
#include "Reflections/hkaiUserEdgeUtilsReflection.cpp"
#include "Reflections/hkaiNavMeshReflection.cpp"
#include "Reflections/hkaiNavMeshInstanceReflection.cpp"
#include "Reflections/hkaiNavMeshPathSearchParametersReflection.cpp"
#include "Reflections/hkaiNavVolumeReflection.cpp"
#include "Reflections/hkaiNavVolumeInstanceReflection.cpp"
#include "Reflections/hkaiNavVolumePathSearchParametersReflection.cpp"
#include "Reflections/hkaiHierarchyUtilsReflection.cpp"
#include "Reflections/hkaiLineOfSightUtilReflection.cpp"
#include "Reflections/hkaiFixOverlappingTrianglesReflection.cpp"
#include "Reflections/hkaiNavMeshGenerationSnapshotReflection.cpp"
#include "Reflections/hkaiNavMeshSimplificationSnapshotReflection.cpp"
#include "Reflections/hkaiNavVolumeGenerationSnapshotReflection.cpp"
#include "Reflections/hkaiSplitGenerationSnapshotReflection.cpp"
#include "Reflections/hkaiSplitGenerationUtilsReflection.cpp"
#include "Reflections/hkaiPathfindingUtilReflection.cpp"
#include "Reflections/hkaiVolumePathfindingUtilReflection.cpp"
#include "Reflections/hkaiWorldReflection.cpp"

/*
 * Havok SDK - Base file, BUILD(#20140618)
 * 
 * Confidential Information of Havok.  (C) Copyright 1999-2014
 * Telekinesys Research Limited t/a Havok. All Rights Reserved. The Havok
 * Logo, and the Havok buzzsaw logo are trademarks of Havok.  Title, ownership
 * rights, and intellectual property rights in the Havok software remain in
 * Havok and/or its suppliers.
 * 
 * Use of this software for evaluation purposes is subject to and indicates
 * acceptance of the End User licence Agreement for this product. A copy of
 * the license is included with this software and is also available from salesteam@havok.com.
 * 
 */
