/*
 *
 * Confidential Information of Telekinesys Research Limited (t/a Havok). Not for disclosure or distribution without Havok's
 * prior written consent. This software contains code, techniques and know-how which is confidential and proprietary to Havok.
 * Product and Trade Secret source code contains trade secrets of Havok. Havok Software (C) Copyright 1999-2014 Telekinesys Research Limited t/a Havok. All Rights Reserved. Use of this software is subject to the terms of an end user license agreement.
 *
 */

//HK_REFLECTION_PARSER_EXCLUDE_FILE

// Autogenerated by generateReflections.py (projectClassList.py)
// Changes will not be lost unless:
// - The workspace is re-generated using build.py
// - The corresponding reflection database (reflection.db) is deleted
// - The --force-output or --force-rebuild option is added to the pre-build generateReflection.py execution

HK_ABSTRACT_CLASS(HK_EXPORT_AI,hkaiAstarCostModifier)
HK_ABSTRACT_CLASS(HK_EXPORT_AI,hkaiAstarEdgeFilter)
HK_ABSTRACT_CLASS(HK_EXPORT_AI,hkaiNavMeshQueryMediator)
HK_ABSTRACT_CLASS(HK_EXPORT_AI,hkaiNavVolumeMediator)
HK_ABSTRACT_CLASS(HK_EXPORT_AI,hkaiPhysicsBodySilhouetteGeneratorBase)
HK_ABSTRACT_CLASS(HK_EXPORT_AI,hkaiSilhouetteGenerator)
HK_ABSTRACT_CLASS(HK_EXPORT_AI,hkaiVolume)
HK_CLASS(HK_EXPORT_AI,hkaiAabbTreeNavVolumeMediator)
HK_CLASS(HK_EXPORT_AI,hkaiAvoidancePairProperties)
HK_CLASS(HK_EXPORT_AI,hkaiAvoidanceProperties)
HK_CLASS(HK_EXPORT_AI,hkaiCarver)
HK_CLASS(HK_EXPORT_AI,hkaiCharacter)
HK_CLASS(HK_EXPORT_AI,hkaiConvexHullSilhouetteMerger)
HK_CLASS(HK_EXPORT_AI,hkaiConvexSilhouetteSet)
HK_CLASS(HK_EXPORT_AI,hkaiCuttingGeometryInfo)
HK_CLASS(HK_EXPORT_AI,hkaiDefaultAstarCostModifier)
HK_CLASS(HK_EXPORT_AI,hkaiDefaultAstarEdgeFilter)
HK_CLASS(HK_EXPORT_AI,hkaiDirectedGraphExplicitCost)
HK_CLASS(HK_EXPORT_AI,hkaiDirectedGraphInstance)
HK_CLASS(HK_EXPORT_AI,hkaiDynamicNavMeshQueryMediator)
HK_CLASS(HK_EXPORT_AI,hkaiDynamicNavVolumeMediator)
HK_CLASS(HK_EXPORT_AI,hkaiEdgePath)
HK_CLASS(HK_EXPORT_AI,hkaiInvertedAabbVolume)
HK_CLASS(HK_EXPORT_AI,hkaiMaterialPainter)
HK_CLASS(HK_EXPORT_AI,hkaiNavMesh)
HK_CLASS(HK_EXPORT_AI,hkaiNavMeshCutter)
HK_CLASS(HK_EXPORT_AI,hkaiNavMeshInstance)
HK_CLASS(HK_EXPORT_AI,hkaiNavMeshPathRequestInfo)
HK_CLASS(HK_EXPORT_AI,hkaiNavVolume)
HK_CLASS(HK_EXPORT_AI,hkaiNavVolumeInstance)
HK_CLASS(HK_EXPORT_AI,hkaiNavVolumePathRequestInfo)
HK_CLASS(HK_EXPORT_AI,hkaiObstacleGenerator)
HK_CLASS(HK_EXPORT_AI,hkaiOverlapManager)
HK_CLASS(HK_EXPORT_AI,hkaiOverlapManagerSectionGeneratorData)
HK_CLASS(HK_EXPORT_AI,hkaiPath)
HK_CLASS(HK_EXPORT_AI,hkaiPathFollowingProperties)
HK_CLASS(HK_EXPORT_AI,hkaiPathfindingUtilFindPathInput)
HK_CLASS(HK_EXPORT_AI,hkaiPathfindingUtilFindPathOutput)
HK_CLASS(HK_EXPORT_AI,hkaiPlaneVolume)
HK_CLASS(HK_EXPORT_AI,hkaiPointCloudSilhouetteGenerator)
HK_CLASS(HK_EXPORT_AI,hkaiSilhouetteMerger)
HK_CLASS(HK_EXPORT_AI,hkaiSimpleObstacleGenerator)
HK_CLASS(HK_EXPORT_AI,hkaiSimpleSilhouetteMerger)
HK_CLASS(HK_EXPORT_AI,hkaiStaticTreeNavMeshQueryMediator)
HK_CLASS(HK_EXPORT_AI,hkaiStreamingCollection)
HK_CLASS(HK_EXPORT_AI,hkaiUserEdgePairArray)
HK_CLASS(HK_EXPORT_AI,hkaiUserEdgeSetupArray)
HK_CLASS(HK_EXPORT_AI,hkaiVolumePathfindingUtilFindPathInput)
HK_CLASS(HK_EXPORT_AI,hkaiVolumePathfindingUtilFindPathOutput)
HK_CLASS(HK_EXPORT_AI,hkaiWorld)
HK_CLASS(HK_EXPORT_AI,hkaiWorldCharacterStepSerializableContext)
HK_STRUCT(HK_EXPORT_AI,hkaiAdaptiveRanger)
HK_STRUCT(HK_EXPORT_AI,hkaiAgentTraversalInfo)
HK_STRUCT(HK_EXPORT_AI,hkaiAstarOutputParameters)
HK_STRUCT(HK_EXPORT_AI,hkaiAvoidancePairPropertiesPairData)
HK_STRUCT(HK_EXPORT_AI,hkaiAvoidanceSolverBoundaryObstacle)
HK_STRUCT(HK_EXPORT_AI,hkaiAvoidanceSolverSphereObstacle)
HK_STRUCT(HK_EXPORT_AI,hkaiDirectedGraphExplicitCostEdge)
HK_STRUCT(HK_EXPORT_AI,hkaiDirectedGraphExplicitCostNode)
HK_STRUCT(HK_EXPORT_AI,hkaiDirectedGraphInstanceFreeBlockList)
HK_STRUCT(HK_EXPORT_AI,hkaiEdgePathEdge)
HK_STRUCT(HK_EXPORT_AI,hkaiEdgePathFollowingCornerInfo)
HK_STRUCT(HK_EXPORT_AI,hkaiGraphPathSearchParameters)
HK_STRUCT(HK_EXPORT_AI,hkaiHierarchyUtils)
HK_STRUCT(HK_EXPORT_AI,hkaiHierarchyUtilsClusterSettings)
HK_STRUCT(HK_EXPORT_AI,hkaiLineOfSightUtil)
HK_STRUCT(HK_EXPORT_AI,hkaiLineOfSightUtilDirectPathInput)
HK_STRUCT(HK_EXPORT_AI,hkaiLineOfSightUtilInputBase)
HK_STRUCT(HK_EXPORT_AI,hkaiLineOfSightUtilLineOfSightInput)
HK_STRUCT(HK_EXPORT_AI,hkaiLineOfSightUtilLineOfSightOutput)
HK_STRUCT(HK_EXPORT_AI,hkaiLocalSteeringInput)
HK_STRUCT(HK_EXPORT_AI,hkaiMovementProperties)
HK_STRUCT(HK_EXPORT_AI,hkaiNavMeshCutterMeshInfo)
HK_STRUCT(HK_EXPORT_AI,hkaiNavMeshCutterSavedConnectivity)
HK_STRUCT(HK_EXPORT_AI,hkaiNavMeshEdge)
HK_STRUCT(HK_EXPORT_AI,hkaiNavMeshFace)
HK_STRUCT(HK_EXPORT_AI,hkaiNavMeshGenerationSnapshot)
HK_STRUCT(HK_EXPORT_AI,hkaiNavMeshPathSearchParameters)
HK_STRUCT(HK_EXPORT_AI,hkaiNavMeshSimplificationSnapshot)
HK_STRUCT(HK_EXPORT_AI,hkaiNavVolumeCell)
HK_STRUCT(HK_EXPORT_AI,hkaiNavVolumeEdge)
HK_STRUCT(HK_EXPORT_AI,hkaiNavVolumeGenerationSnapshot)
HK_STRUCT(HK_EXPORT_AI,hkaiNavVolumeInstanceCellInstance)
HK_STRUCT(HK_EXPORT_AI,hkaiNavVolumePathSearchParameters)
HK_STRUCT(HK_EXPORT_AI,hkaiOverlapManagerSection)
HK_STRUCT(HK_EXPORT_AI,hkaiOverlappingTriangles)
HK_STRUCT(HK_EXPORT_AI,hkaiOverlappingTrianglesSettings)
HK_STRUCT(HK_EXPORT_AI,hkaiPathPathPoint)
HK_STRUCT(HK_EXPORT_AI,hkaiPathfindingUtil)
HK_STRUCT(HK_EXPORT_AI,hkaiPathfindingUtilFindGraphPathInput)
HK_STRUCT(HK_EXPORT_AI,hkaiPersistentEdgeKey)
HK_STRUCT(HK_EXPORT_AI,hkaiPersistentFaceKey)
HK_STRUCT(HK_EXPORT_AI,hkaiReferenceFrame)
HK_STRUCT(HK_EXPORT_AI,hkaiReferenceFrameAndExtrusion)
HK_STRUCT(HK_EXPORT_AI,hkaiSearchParameters)
HK_STRUCT(HK_EXPORT_AI,hkaiSearchParametersBufferSizes)
HK_STRUCT(HK_EXPORT_AI,hkaiSearchParametersSearchBuffers)
HK_STRUCT(HK_EXPORT_AI,hkaiSilhouetteGenerationParameters)
HK_STRUCT(HK_EXPORT_AI,hkaiSilhouetteGeneratorSectionContext)
HK_STRUCT(HK_EXPORT_AI,hkaiSilhouetteReferenceFrame)
HK_STRUCT(HK_EXPORT_AI,hkaiSplitGenerationSnapshot)
HK_STRUCT(HK_EXPORT_AI,hkaiSplitGenerationUtils)
HK_STRUCT(HK_EXPORT_AI,hkaiSplitGenerationUtilsSettings)
HK_STRUCT(HK_EXPORT_AI,hkaiStreamingCollectionInstanceInfo)
HK_STRUCT(HK_EXPORT_AI,hkaiStreamingSet)
HK_STRUCT(HK_EXPORT_AI,hkaiStreamingSetGraphConnection)
HK_STRUCT(HK_EXPORT_AI,hkaiStreamingSetNavMeshConnection)
HK_STRUCT(HK_EXPORT_AI,hkaiStreamingSetVolumeConnection)
HK_STRUCT(HK_EXPORT_AI,hkaiUserEdgeUtils)
HK_STRUCT(HK_EXPORT_AI,hkaiUserEdgeUtilsObb)
HK_STRUCT(HK_EXPORT_AI,hkaiUserEdgeUtilsUserEdgePair)
HK_STRUCT(HK_EXPORT_AI,hkaiUserEdgeUtilsUserEdgeSetup)
HK_STRUCT(HK_EXPORT_AI,hkaiVolumePathfindingUtil)

/*
 * Havok SDK - Base file, BUILD(#20140618)
 * 
 * Confidential Information of Havok.  (C) Copyright 1999-2014
 * Telekinesys Research Limited t/a Havok. All Rights Reserved. The Havok
 * Logo, and the Havok buzzsaw logo are trademarks of Havok.  Title, ownership
 * rights, and intellectual property rights in the Havok software remain in
 * Havok and/or its suppliers.
 * 
 * Use of this software for evaluation purposes is subject to and indicates
 * acceptance of the End User licence Agreement for this product. A copy of
 * the license is included with this software and is also available from salesteam@havok.com.
 * 
 */
